# Tasks 1-2

In [ ]:
import numpy as np

In [ ]:
#setting up the variables
u = np.array([1, 0, 0, 0, 0, 0, 0, 0])
k = np.array([1, 0, 0, 0, 0, 0, 0, 0])
x = np.array([4, 0, 0, 9, 7, 0, 0, 3])
p = 11

#generation keys
def subkey_gen(k):
    k1 = np.array([k[0], k[2], k[4], k[6]])
    k2 = np.array([k[0], k[1], k[2], k[3]])
    k3 = np.array([k[0], k[3], k[4], k[7]])
    k4 = np.array([k[0], k[3], k[5], k[6]])
    k5 = np.array([k[0], k[2], k[5], k[7]])
    k6 = np.array([k[2], k[3], k[4], k[5]])
    set_of_subkeys = np.array([k1, k2, k3, k4, k5, k6])
    return set_of_subkeys
def inverse_subkey_gen(k):
    set_of_subkeys = subkey_gen(k)
    set_of_subkeys = set_of_subkeys[::-1]
    return set_of_subkeys

#def subkey sum
def subkey_sum(w, k):
    v = np.zeros([8])
    key = np.concatenate((k,k), axis = None)
    for i in range(0, 8):
        v[i] = w[i] + key[i]
    return v % p
#def inverse subkey sum:
def inverse_subkey_sum(v, k):
    w = np.zeros([8])
    key = np.concatenate((k,k), axis = None)
    for i in range(0, 8):
        w[i] = v[i] - key[i]
    return w % p

#def substitution
def substitution(v):
    y = np.zeros([8])
    for i in range(0, 8):
        y[i] = v[i] + v[i]
    return y % p
#def inverse substitution
def inverse_substitution(y):
    v = np.zeros([8])
    for i in range(0, 8):
        for j in range(0, p):
            if (j + j) % p == y[i]:
                v[i] = j
    return v % p

#def transposition
def transposition(y):
    y_copy = y
    y_copy = y_copy[4:]
    y_copy = y_copy[::-1]
    z = np.zeros([8])
    for i in range(0, 4):
        z[i] = y[i]
        z[i+4] = y_copy[i]
    return z % p
#def inverse transposition
def inverse_transposition(z):
    z_copy = z
    z_copy = z_copy[4:]
    z_copy = z_copy[::-1]
    y = np.zeros([8])
    for i in range(0, 4):
        y[i] = z[i]
        y[i+4] = z_copy[i]
    return y % p

#def linear
def linear(z):
    matrix = np.array([[2, 5], [1, 7]])
    z_matrix = np.array([[z[0], z[1], z[2], z[3]], [z[4], z[5], z[6], z[7]]])
    w = np.matmul(matrix, z_matrix)
    w = w.flatten()
    return w % p
#def inverse linear
def inverse_linear(w):
    matrix = np.array([[2, 8], [6, 10]])
    w_matrix = np.array([[w[0], w[1], w[2], w[3]], [w[4], w[5], w[6], w[7]]])
    z = np.matmul(matrix, w_matrix)
    z = z.flatten()
    return z % p

#Task 1 - Implement a simple AES-like encryptor
def encrypt(u, k):
    subkeys = subkey_gen(k)
    for i in range(0,6):
        if i == 0:
            w = subkey_sum(u, np.array(subkeys[i]))
        else:
            w = subkey_sum(w, np.array(subkeys[i]))
        if i<5 and i != 4:
            y = substitution(w)
            z = transposition(y)
            w = linear(z)
        if i == 4:
            y = substitution(w)
            z = transposition(y)
            w = z
    return w % p

#Task 2 - Implement a simple AES-like decryptor
def decrypt(x, k):
    subkeys = inverse_subkey_gen(k)
    for i in range(0,6):
        if i == 0:
            w = inverse_subkey_sum(x, np.array(subkeys[i]))
        elif i == 1:
            z = w
            y = inverse_transposition(z)
            w = inverse_substitution(y)
            z = inverse_subkey_sum(w, np.array(subkeys[i]))
        elif i >= 2:
            w = inverse_linear(z)
            y = inverse_transposition(w)
            w = inverse_substitution(y)
            z = inverse_subkey_sum(w, np.array(subkeys[i]))
    return z % p

In [ ]:
print("Task 1 - Implement a simple AES-like encryptor")
print("x = ", x)
print("k = ", k)
print("u = ", u)
print("p = ", p)
print("Encryption: ", encrypt(u, k).astype('int'))
print("")
print("Task 2 - Implement a simple AES-like decryptor")
print("x = ", x)
print("k = ", k)
print("u = ", u)
print("p = ", p)
print("Decryption: ", decrypt(x, k).astype('int'))
print("")
print("Proof of correctness")
print("Decryption of encryption: ", decrypt(encrypt(u, k), k).astype('int'))
print("Encryption of decryption: ", encrypt(decrypt(x, k), k).astype('int'))

Task 1 - Implement a simple AES-like encryptor
x =  [4 0 0 9 7 0 0 3]
k =  [1 0 0 0 0 0 0 0]
u =  [1 0 0 0 0 0 0 0]
p =  11
Encryption:  [4 0 0 9 7 0 0 3]

Task 2 - Implement a simple AES-like decryptor
x =  [4 0 0 9 7 0 0 3]
k =  [1 0 0 0 0 0 0 0]
u =  [1 0 0 0 0 0 0 0]
p =  11
Decryption:  [1 0 0 0 0 0 0 0]

Proof of correctness
Decryption of encryption:  [1 0 0 0 0 0 0 0]
Encryption of decryption:  [4 0 0 9 7 0 0 3]


# Task 3

In [ ]:
#define orthonormal basis

e_1 = np.array([1, 0, 0, 0, 0, 0, 0, 0])
e_2 = np.array([0, 1, 0, 0, 0, 0, 0, 0])
e_3 = np.array([0, 0, 1, 0, 0, 0, 0, 0])
e_4 = np.array([0, 0, 0, 1, 0, 0, 0, 0])
e_5 = np.array([0, 0, 0, 0, 1, 0, 0, 0])
e_6 = np.array([0, 0, 0, 0, 0, 1, 0, 0])
e_7 = np.array([0, 0, 0, 0, 0, 0, 1, 0])
e_8 = np.array([0, 0, 0, 0, 0, 0, 0, 1])

\begin{equation}
\text{Ecrypt}(u,k)=x=AK+Bu \mod p
\end{equation}

Computing the matrix $A$

In [ ]:
zeros = np.zeros([8])

e = [e_1,e_2,e_3,e_4,e_5,e_6,e_7,e_8]

a=[]

for e_i in e:
  a_i = encrypt(zeros, e_i)
  a.append(a_i)

A = np.column_stack(a)
print(A.astype('int'))

[[ 9  0  1  6  0  0  1 10]
 [ 0  8  6  2  2  9  0  0]
 [ 0  6  0  8  3 10  0  0]
 [ 6  0  0  8  0  1  6  6]
 [ 2  0  1 10  0  0  1  3]
 [ 0  1  8  4  9  6  0  0]
 [ 0 10  0  5  7  6  0  0]
 [ 3  0  0  1  0  1  4  8]]


Computing the matrix $B$

In [ ]:
b=[]

for e_i in e:
  b_i = encrypt(e_i,zeros)
  b.append(b_i)

B = np.column_stack(b)
print(B.astype('int'))

[[6 0 0 3 3 0 0 0]
 [0 6 3 0 0 3 0 0]
 [0 3 6 0 0 0 3 0]
 [3 0 0 6 0 0 0 3]
 [5 0 0 0 4 0 0 8]
 [0 5 0 0 0 4 8 0]
 [0 0 5 0 0 8 4 0]
 [0 0 0 5 8 0 0 4]]


We see if the linear approximmation returns the same encryption of the function Encryption

In [ ]:
((np.matmul(A, k) + np.matmul(B, u)) % p).astype('int')

array([4, 0, 0, 9, 7, 0, 0, 3])

# Task 4

In [ ]:
from numpy.linalg import inv

u = np.array([1, 0, 0, 0, 0, 0, 0, 0])

x = np.array([4, 0, 0, 9, 7, 0, 0, 3])

#### Specific Example 

In [ ]:
# Specific Example

matrix = ([[2, 5], [1, 7]])

def modularInverse(M):
    
    M_star = inv(M) #inverse of M in R
    #print(M_star)
    det = round(np.linalg.det(M))#determinant of M in R
    #print(det)
    M_tilda = M_star * det #M_tilda in R
    #print(M_tilda)
    det_modular_inverse = pow(int(det), -1, p)
    #print(det_modular_inverse)
    M_modular_inverse = (M_tilda * det_modular_inverse % p).astype('int')
    #print(M_modular_inverse)
    return M_modular_inverse

modularInverse(matrix)

array([[ 2,  8],
       [ 6, 10]])

#### General Case

Due to `np.linalg.det` function, we computed the inverse of the matrix $A$ with the online tool [https://planetcalc.com/3324/](https://planetcalc.com/3324/)

In [ ]:
A_star = ([[10,	9,	6,	10,	2,	0,	9,	4], [8,	0,	9,	4,	4,	4,	2,	2],
           [3,	10,	9,	7,	7,	1,	3,	9], [0,	2,	7,	0,	0,	4,	7,	0],
           [2,	5,	8,	1,	1,	0,	0,	6], [10,	9,	1,	5,	5,	1,	2,	8],
           [5,	7,	3,	3,	9,	4,	1,	6], [9,	0,	9,	1,	1,	7,	6,	7]])

In [ ]:
u_1 = np.array([5,7,7,6,0,7,8,8])
x_1 = np.array([7,7,8,1,2,6,5,9])

u_2 = np.array([1,3,3,1,0,6,2,7])
x_2 = np.array([1,1,9,0,7,0,8,2])

u_3 = np.array([5,10,0,3,5,1,1,1]) 
x_3 = np.array([2,8,9,6,10,7,4,6])

u_4 = np.array([6,3,9,1,5,7,9,4])
x_4 = np.array([2,0,0,6,6,5,8,8])

u_5 = np.array([0,8,9,4,8,10,5,9])
x_5 = np.array([6,6,3,10,6,10,5,1])

u = np.array([u_1, u_2, u_3, u_4, u_5])
x = np.array([x_1, x_2, x_3, x_4, x_5])

for i in range(0,5):
    k = np.matmul(A_star, (x[i]-np.matmul(B,u[i]))) % p

#encrypt and decrypt
#Proof of correctness
print("Encryption and Decryption")
print("")
for i in range(0,5):
    print("k = ", k.astype('int'))
    print("u = ", u[i])
    print("x = ", x[i])
    print("Encryption(u,k): ", encrypt(u[i], k).astype('int'))
    print("Decryption(x,k): ", decrypt(x[i], k).astype('int'))
    print("")

Encryption and Decryption

k =  [ 8 10  2  7  6  4  9  1]
u =  [5 7 7 6 0 7 8 8]
x =  [7 7 8 1 2 6 5 9]
Encryption(u,k):  [7 7 8 1 2 6 5 9]
Decryption(x,k):  [5 7 7 6 0 7 8 8]

k =  [ 8 10  2  7  6  4  9  1]
u =  [1 3 3 1 0 6 2 7]
x =  [1 1 9 0 7 0 8 2]
Encryption(u,k):  [1 1 9 0 7 0 8 2]
Decryption(x,k):  [1 3 3 1 0 6 2 7]

k =  [ 8 10  2  7  6  4  9  1]
u =  [ 5 10  0  3  5  1  1  1]
x =  [ 2  8  9  6 10  7  4  6]
Encryption(u,k):  [ 2  8  9  6 10  7  4  6]
Decryption(x,k):  [ 5 10  0  3  5  1  1  1]

k =  [ 8 10  2  7  6  4  9  1]
u =  [6 3 9 1 5 7 9 4]
x =  [2 0 0 6 6 5 8 8]
Encryption(u,k):  [2 0 0 6 6 5 8 8]
Decryption(x,k):  [6 3 9 1 5 7 9 4]

k =  [ 8 10  2  7  6  4  9  1]
u =  [ 0  8  9  4  8 10  5  9]
x =  [ 6  6  3 10  6 10  5  1]
Encryption(u,k):  [ 6  6  3 10  6 10  5  1]
Decryption(x,k):  [ 0  8  9  4  8 10  5  9]



# Task 5

In [ ]:
#setting up the variables
u = np.array([1, 0, 0, 0, 0, 0, 0, 0])
k = np.array([1, 0, 0, 0, 0, 0, 0, 0])
x = np.array([9, 0, 0, 0, 5, 0, 0, 6])
p = 11

#generation keys
def subkey_gen(k):
    k1 = np.array([k[0], k[2], k[4], k[6]])
    k2 = np.array([k[0], k[1], k[2], k[3]])
    k3 = np.array([k[0], k[3], k[4], k[7]])
    k4 = np.array([k[0], k[3], k[5], k[6]])
    k5 = np.array([k[0], k[2], k[5], k[7]])
    k6 = np.array([k[2], k[3], k[4], k[5]])
    set_of_subkeys = np.array([k1, k2, k3, k4, k5, k6])
    return set_of_subkeys
def inverse_subkey_gen(k):
    set_of_subkeys = subkey_gen(k)
    set_of_subkeys = set_of_subkeys[::-1]
    return set_of_subkeys

#def subkey sum:
def subkey_sum(w, k):
    v = np.zeros([8])
    key = np.concatenate((k,k), axis = None)
    for i in range(0, 8):
        v[i] = w[i] + key[i]
    return v % p
#def inverse subkey sum:
def inverse_subkey_sum(v, k):
    w = np.zeros([8])
    key = np.concatenate((k,k), axis = None)
    for i in range(0, 8):
        w[i] = v[i] - key[i]
    return w % p

#def substitution:
def substitution(v):
    y = np.zeros([8])
    map = {0:0, 1:2, 2:4, 3:8, 4:6, 5:10, 6:1, 7:3, 8:5, 9:7, 10:9}
    for i in range(0, 8):
        y[i] = map[v[i]]
    return y % p
#def inverse substitution:
def inverse_substitution(y):
    v = np.zeros([8])
    map = {0:0, 1:6, 2:1, 3:7, 4:2, 5:8, 6:4, 7:9, 8:3, 9:10, 10:5}
    for i in range(0, 8):
        v[i] = map[y[i]]
    return v % p

#def transposition:
def transposition(y):
    y_copy = y
    y_copy = y_copy[4:]
    y_copy = y_copy[::-1]
    z = np.zeros([8])
    for i in range(0, 4):
        z[i] = y[i]
        z[i+4] = y_copy[i]
    return z % p
#def inverse transposition:
def inverse_transposition(z):
    z_copy = z
    z_copy = z_copy[4:]
    z_copy = z_copy[::-1]
    y = np.zeros([8])
    for i in range(0, 4):
        y[i] = z[i]
        y[i+4] = z_copy[i]
    return y % p

#def linear
def linear(z):
    matrix = np.array([[2, 5], [1, 7]])
    z_matrix = np.array([[z[0], z[1], z[2], z[3]], [z[4], z[5], z[6], z[7]]])
    w = np.matmul(matrix, z_matrix)
    w = w.flatten()
    return w % p
#def inverse linear
def inverse_linear(w):
    matrix = np.array([[2, 8], [6, 10]])
    w_matrix = np.array([[w[0], w[1], w[2], w[3]], [w[4], w[5], w[6], w[7]]])
    z = np.matmul(matrix, w_matrix)
    z = z.flatten()
    return z % p

#Task 5 - Implement a simple AES-like encryptor
def encrypt(u, k):
    subkeys = subkey_gen(k)
    for i in range(0,6):
        if i == 0:
            w = subkey_sum(u, np.array(subkeys[i]))
        else:
            w = subkey_sum(w, np.array(subkeys[i]))
        if i<5 and i != 4:
            y = substitution(w)
            z = transposition(y)
            w = linear(z)
        if i == 4:
            y = substitution(w)
            z = transposition(y)
            w = z
    return w % p

#Task 5 - Implement a simple AES-like decryptor
def decrypt(x, k):
    subkeys = inverse_subkey_gen(k)
    for i in range(0,6):
        if i == 0:
            w = inverse_subkey_sum(x, np.array(subkeys[i]))
        elif i == 1:
            z = w
            y = inverse_transposition(z)
            w = inverse_substitution(y)
            z = inverse_subkey_sum(w, np.array(subkeys[i]))
        elif i >= 2:
            w = inverse_linear(z)
            y = inverse_transposition(w)
            w = inverse_substitution(y)
            z = inverse_subkey_sum(w, np.array(subkeys[i]))
    return z % p

In [ ]:
print("Task 5 - Implement a simple AES-like encryptor")
print("x = ", x)
print("k = ", k)
print("u = ", u)
print("p = ", p)
print("Encryption: ", encrypt(u, k).astype('int'))
print("")
print("Task 5 - Implement a simple AES-like decryptor")
print("x = ", x)
print("k = ", k)
print("u = ", u)
print("p = ", p)
print("Decryption: ", decrypt(x, k).astype('int'))
print("")
print("Proof of correctness")
print("Decryption of encryption: ", decrypt(encrypt(u, k), k).astype('int'))
print("Encryption of decryption: ", encrypt(decrypt(x, k), k).astype('int'))

Task 5 - Implement a simple AES-like encryptor
x =  [9 0 0 0 5 0 0 6]
k =  [1 0 0 0 0 0 0 0]
u =  [1 0 0 0 0 0 0 0]
p =  11
Encryption:  [9 0 0 0 5 0 0 6]

Task 5 - Implement a simple AES-like decryptor
x =  [9 0 0 0 5 0 0 6]
k =  [1 0 0 0 0 0 0 0]
u =  [1 0 0 0 0 0 0 0]
p =  11
Decryption:  [1 0 0 0 0 0 0 0]

Proof of correctness
Decryption of encryption:  [1 0 0 0 0 0 0 0]
Encryption of decryption:  [9 0 0 0 5 0 0 6]


# Task 7

In [ ]:
#setting up the variables
u = np.array([1, 0, 0, 0, 0, 0, 0, 0])
k = np.array([1, 0, 0, 0])
x = np.array([5, 0, 3, 2, 5, 2, 1, 1])
p = 11

#generation keys
def subkey_gen(k):
    k1 = np.array([k[0], k[1], k[2], k[3]])
    k2 = np.array([k[0], k[1], k[3], k[2]])
    k3 = np.array([k[1], k[2], k[3], k[0]])
    k4 = np.array([k[0], k[3], k[1], k[2]])
    k5 = np.array([k[2], k[3], k[0], k[1]])
    k6 = np.array([k[1], k[3], k[0], k[2]])
    set_of_subkeys = np.array([k1, k2, k3, k4, k5, k6])
    return set_of_subkeys
def inverse_subkey_gen(k):
    set_of_subkeys = subkey_gen(k)
    set_of_subkeys = set_of_subkeys[::-1]
    return set_of_subkeys

#def subkey sum:
def subkey_sum(w, k):
    v = np.zeros([8])
    key = np.concatenate((k,k), axis = None)
    for i in range(0, 8):
        v[i] = w[i] + key[i]
    return v % p
#def inverse subkey sum:
def inverse_subkey_sum(v, k):
    w = np.zeros([8])
    key = np.concatenate((k,k), axis = None)
    for i in range(0, 8):
        w[i] = v[i] - key[i]
    return w % p

#def find_inverse of a vector:
def find_inverse(v):
    for i in range(len(v)):
        for j in range(1, p):
            if (v[i] * j) % p == 1:
                v[i] = j
                break
    return v
#def substitution
def substitution(v):
    y = np.zeros([8])
    v = find_inverse(v)
    for i in range(0, 8):
        y[i] = 2*v[i]
    return y % p
#def inverse substitution
def inverse_substitution(y):
    v = np.zeros([8])
    for i in range(0, 8):
        for j in range(0, p):
            if (j + j) % p == y[i]:
                v[i] = j
                break
    v = find_inverse(v)
    return v % p

#def transposition
def transposition(y):
    y_copy = y
    y_copy = y_copy[4:]
    y_copy = y_copy[::-1]
    y = np.concatenate((y[:4], y_copy), axis = None)
    return y
#def inverse transposition
def inverse_transposition(z):
    z_copy = z
    z_copy = z_copy[4:]
    z_copy = z_copy[::-1]
    z = np.concatenate((z[:4], z_copy), axis = None)
    return z

#def linear
def linear(z):
    matrix = np.array([[2, 5], [1, 7]])
    z_matrix = np.array([[z[0], z[1], z[2], z[3]], [z[4], z[5], z[6], z[7]]])
    w = np.matmul(matrix, z_matrix)
    w = w.flatten()
    return w % p
#def inverse linear
def inverse_linear(w):
    matrix = np.array([[2, 8], [6, 10]])
    w_matrix = np.array([[w[0], w[1], w[2], w[3]], [w[4], w[5], w[6], w[7]]])
    z = np.matmul(matrix, w_matrix)
    z = z.flatten()
    return z % p

#Task 7 - Implement a simple AES-like encryptor
def encrypt(u, k):
    subkeys = subkey_gen(k)
    for i in range(0,6):
        if i == 0:
            w = subkey_sum(u, np.array(subkeys[i]))
        else:
            w = subkey_sum(w, np.array(subkeys[i]))
        if i<5 and i != 4:
            y = substitution(w)
            z = transposition(y)
            w = linear(z)
        if i == 4:
            y = substitution(w)
            z = transposition(y)
            w = z
    return w % p

#Task 7 - Implement a simple AES-like decryptor
def decrypt(x, k):
    subkeys = inverse_subkey_gen(k)
    for i in range(0,6):
        if i == 0:
            w = inverse_subkey_sum(x, np.array(subkeys[i]))
        elif i == 1:
            z = w
            y = inverse_transposition(z)
            w = inverse_substitution(y)
            z = inverse_subkey_sum(w, np.array(subkeys[i]))
        elif i >= 2:
            w = inverse_linear(z)
            y = inverse_transposition(w)
            w = inverse_substitution(y)
            z = inverse_subkey_sum(w, np.array(subkeys[i]))
    return z % p

In [ ]:
print("Task 7 - Implement a simple AES-like encryptor")
print("x = ", x)
print("k = ", k)
print("u = ", u)
print("p = ", p)
print("Encryption: ", encrypt(u, k).astype('int'))
print("")
print("Task 7 - Implement a simple AES-like decryptor")
print("x = ", x)
print("k = ", k)
print("u = ", u)
print("p = ", p)
print("Decryption: ", decrypt(x, k).astype('int'))
print("")
print("Proof of correctness:")
print("Decryption of encryption: ", decrypt(encrypt(u, k), k).astype('int'))
print("Encryption of decryption: ", encrypt(decrypt(x, k), k).astype('int'))

Task 7 - Implement a simple AES-like encryptor
x =  [5 0 3 2 5 2 1 1]
k =  [1 0 0 0]
u =  [1 0 0 0 0 0 0 0]
p =  11
Encryption:  [5 0 3 2 5 2 1 1]

Task 7 - Implement a simple AES-like decryptor
x =  [5 0 3 2 5 2 1 1]
k =  [1 0 0 0]
u =  [1 0 0 0 0 0 0 0]
p =  11
Decryption:  [1 0 0 0 0 0 0 0]

Proof of correctness:
Decryption of encryption:  [1 0 0 0 0 0 0 0]
Encryption of decryption:  [5 0 3 2 5 2 1 1]


# Task 8

Let's define our plaintexts and ciphertexts

In [ ]:
u1 = [7, 5, 3, 3, 1, 5, 4, 8]
x1 = [3, 4, 9, 5, 3, 4, 7, 10]

u2 = [2, 6, 0, 7, 8, 2, 8, 1]
x2 = [1, 1, 5, 4, 3, 9, 7, 7]

u3 = [7, 4, 2, 6, 6, 8, 7, 8]
x3 = [3, 3, 5, 3, 8, 6, 9, 3]

u4 = [3, 7, 5, 3, 1, 10, 3, 1]
x4 = [4, 7, 5, 9, 4, 3, 10, 10]

u5 = [2, 5, 8, 7, 9, 5, 3, 8]
x5 = [8, 9, 6, 6, 3, 9, 7, 7]

Implementing the "Meet in the middle" attack against the concatenation of two
instances of the non linear simplified AES-like cipher

In [ ]:
def key_gen():
    key = np.random.randint(0, p, 4)
    return key

In [ ]:
dictionary_1 = {}
dictionary_2 = {}

thousand_keys_1 = []
for i in range(0, 80000):
  thousand_keys_1.append(key_gen())

thousand_keys_1 = np.array(thousand_keys_1)
thousand_keys_1 = np.unique(thousand_keys_1, axis=0).tolist()
print(len(thousand_keys_1))

thousand_keys_2 = []
for i in range(0, 80000):
  thousand_keys_2.append(key_gen())

thousand_keys_2 = np.array(thousand_keys_2)
thousand_keys_2 = np.unique(thousand_keys_2, axis=0).tolist()
print(len(thousand_keys_2))

print("Task 8")
print("u1 = ", u1)
print("x1 = ", x1)
print("p = ", p)

# compute all the encryption of u1 with the keys in thousand_keys_1
for i in range(0, len(thousand_keys_1)):
  # associate to the dictionary the key and the ciphertext
  dictionary_1[i] = encrypt(u1, thousand_keys_1[i])
  
# compute all the decryption of x1 with the keys in thousand_keys_2
for i in range(0, len(thousand_keys_2)):
  dictionary_2[i] = decrypt(x1, thousand_keys_2[i])

dict(sorted(dictionary_1.items(), key=lambda item: item[1].all()))
dict(sorted(dictionary_2.items(), key=lambda item: item[1].all()))

print("Dictionaries created and sorted")
print("----------------------------------")
print("Testing for matches...")

for i in range(0, len(thousand_keys_1)):
  for j in range(0, len(thousand_keys_2)):
    if np.array_equal(dictionary_1[i], dictionary_2[j]):
      print("Found a match!")
      print("Key 1 = ", thousand_keys_1[i])
      print("Key 2 = ", thousand_keys_2[j])
      print("Ciphertext = ", dictionary_1[i])
      print("Plaintext = ", dictionary_2[j])
      break

14578
14565
Task 8
u1 =  [7, 5, 3, 3, 1, 5, 4, 8]
x1 =  [3, 4, 9, 5, 3, 4, 7, 10]
p =  11
Dictionaries created and sorted
----------------------------------
Testing for matches...
Found a match!
Key 1 =  [10, 7, 2, 2]
Key 2 =  [5, 4, 6, 0]
Ciphertext =  [ 2. 10.  9.  2.  0.  2.  1.  5.]
Plaintext =  [ 2. 10.  9.  2.  0.  2.  1.  5.]


The idea was to create pairs of keys, encipher the plaintext with the first one and decipher the ciphertext with the second one, and look for the couple of keys for which the enciphered / deciphered messages coincided. That is our target pair of keys.